version: 0.2
phases:
  pre_build:
    commands:
      - echo ******************************   STEP PRE_BUILD  ******************************
      - echo ******************************   Installing source NPM dependencies...   ******************************
      - npm install
      - npx cap add android
      - echo ******************************   FINISH STEP PRE_BUILD  ******************************
  build:
    commands:
      - echo ******************************   STEP BUILD  ******************************
      - echo ******************************   Build started on `date` ******************************
      - echo Compiling the dist folder
      - echo ******************************   STARTING BUILDING ANDROID PLATFORM  ******************************
      - npx cap sync
      - npx cap copy
      - cd android && ./gradlew assembleDebug
      - echo ******************************   FINISH STEP BUILD  ******************************
artifacts:
  files:
    - 'android/app/build/outputs/apk/debug/*.apk'
