version: 0.2
phases:
  pre_build:
    commands:
      - echo ******************************   STEP PRE_BUILD  ******************************
      - echo ******************************   Installing source NPM dependencies...   ******************************
      - export ANDROID_SDK_ROOT=/usr/lib/android-sdk
      - export CURRENT_PATH=$PWD
      # Update libs
      - apt update
      - apt-get update
      - apt install unzip -y
      - apt install curl -y
      # Headless Chrome-browser
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7 libgbm1 libu2f-udev
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
      - adduser test
      - su - test npm run lint
      - su - test npm run test:ci
      - npm install
      - npx cap add android
      - cp AndroidManifest.xml ./android/app/src/main
      - echo ******************************   FINISH STEP PRE_BUILD  ******************************
  build:
    commands:
      - echo ******************************   STEP BUILD  ******************************
      - echo ******************************   Build started on `date` ******************************
      - echo Compiling the dist folder
      - echo ******************************   STARTING BUILDING ANDROID PLATFORM  ******************************
      - npx cap sync
      - npx cap copy

      
      - sudo mkdir -p $ANDROID_SDK_ROOT
      - sudo apt install openjdk-8-jdk -y
      - cd $ANDROID_SDK_ROOT
      - curl --location --show-error  --url "https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip" -o "$ANDROID_SDK_ROOT/commandlinetools-linux-6858069_latest.zip"
      - unzip $ANDROID_SDK_ROOT/commandlinetools-linux-6858069_latest.zip -d $ANDROID_SDK_ROOT/cmdline-tools
      - mv cmdline-tools/cmdline-tools/ cmdline-tools/tools
      - PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
      - echo var-path =   $PATH
      - cd $ANDROID_SDK_ROOT/cmdline-tools/tools/bin
      - yes | sdkmanager --licenses
      - cd $CURRENT_PATH/android
      - chmod 777 gradlew
      - ./gradlew assembleDebug
      - echo ******************************   FINISH STEP BUILD  ******************************
artifacts:
  files:
    - '*.apk'
  base-directory: 'android/app/build/outputs/apk/debug/'
